### ISSUE TITLE
Outstanding!

### ISSUE THREAD

**Issue by scott-wyatt** [ubilabs/node-formatted-stream#2]
After spending the last 24 hours banging my head against the wall, I googled formatted streams in node and found this project.  I have exceptionally large XLSX files that need to be converted to JSON with node, and this worked! I will help however I can. Well done! (please feel free to close this, just couldn't hold back on my excitement)

**Comment by Caerostris** [comment]
Glad to hear this, @scott-wyatt! Thanks for the feedback, we really appreciate it!
